version: 2
updates:
- package-ecosystem: maven
  directory: "/powerunit"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.apache.maven.plugins:maven-invoker-plugin
    versions:
    - 3.2.1
