language: java
jdk:
- oraclejdk8
sudo: false
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
script: 
  - '[ ${TRAVIS_PULL_REQUEST} = ''false'' -a ${TRAVIS_BRANCH} = ''master'' ] && (cd powerunit && travis_wait 120 mvn clean install site -Psite --settings ../target/travis/settings.xml) || (cd powerunit && travis_wait 120 mvn clean install --settings ../target/travis/settings.xml) '
after_success:
- "(cd powerunit && mvn jacoco:report)"
- "bash <(curl -s https://codecov.io/bash)"
- "(cd powerunit && mvn org.apache.maven.plugins:maven-dependency-plugin:copy -Dartifact=com.codacy:codacy-coverage-reporter:4.0.0:jar:assembly -Dtransitive -DoutputDirectory=target/dependency)"
- "(cd powerunit/target/dependency && java -jar codacy-coverage-reporter-4.0.0-assembly.jar report -l Java -r ../site/jacoco/jacoco.xml)"
env:
  global:
  - secure: kX7y1PhsuTRW2GGXGkg88x5HmdoQ1uKnK1M+/y2YYNSu7boLZ+8iLwM07Nb+1WILadrWP9AxWU+8EEhq2+p8bO9wZo3uxcBz7I0Qw2UURJZE6kSMx1sdnvqWEul1ySgvFYi0Ynph6v7W8cUhEF3QzUcMs/1P9PmbE5lpl8KUg6o=
  - secure: J7sLSRJ15Xu02BO4t0b0vx2g4OSEbxN5OjN7cQDWAz0PMIhStZSrRu/m37QwFV3dl1WoSRLJAFGAoyA7Zx3OOgidyTQk2KO1U0UrPOI8Qk8mtGOf5Yc4bgdWbFQD9vDX4PlpMR/xNcv767Cpo6wuejbo9qmWWjrNiQMRaHmEZxA=
  - secure: Lp6ppFsbHDXwcRca5vMne63bNH46Pliy+rgQK+eN5P9zjDm02Kmk4xjZ0hPNoomYnAxyp8dIodyRkmIqKM/AqlfomMEoE2QPfyOfRKiaqy2Jk1i/1tc6VhsbkARSkeYNaA76tWAG4Ee4Be+oNKrGTt6ynApeWLhK+ZslieDba80=
